name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        run: |
          rustup update
          rustup target add wasm32-wasi
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build wasm
        run: cargo build --release
      - name: Save tag data
        run: |
          echo "Git ref: ${{ github.ref }}"
          CONTENTS="$(git for-each-ref ${{ github.ref }} --format='%(contents)')"
          echo "RELEASE_HEADER=$(sed '3q;d' "$CONTENTS")" >> "$GITHUB_ENV"
          echo "RELEASE_BODY=$(tail -n +5 "$CONTENTS")" >> "$GITHUB_ENV"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.RELEASE_HEADER }}
          # consider body_path for changelog document
          body: ${{ env.RELEASE_BODY }}
          files: target/wasm32-wasi/release/zellaunch.wasm
          draft: false
          prerelease: false
