name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
      - name: Build wasm
        run: cargo build --release
      - name: Save tag data
        id: tag_data
        run: |
          echo "::set-output name=header::$(git for-each-ref ${{ github.ref }} --format='%(contents:subject)')"
          echo "::set-output name=body::$(git for-each-ref ${{ github.ref }} --format='%(contents:body)')"
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.tag_data.outputs.header }}
          # consider body_path for changelog document
          body: ${{ steps.tag_data.outputs.body }}
          files: target/wasm32-wasi/release/zellaunch.wasm
          draft: false
          prerelease: false
