name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Rust
        run: |
          rustup update
          rustup target add wasm32-wasi
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Build wasm
        run: cargo build --release
      - name: Save tag data
        run: |
          echo "Git ref: ${{ github.ref }}"
            echo "RELEASE_HEADER=$(git tag -l --format='%(contents:subject)' ${{ github.ref }})" >> "$GITHUB_ENV"
            echo "RELEASE_BODY=$(git tag -l --format='%(contents:body)' ${{ github.ref}})" >> "$GITHUB_ENV"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.RELEASE_HEADER }}
          # consider body_path for changelog document
          body: ${{ env.RELEASE_BODY }}
          files: target/wasm32-wasi/release/zellaunch.wasm
          draft: false
          prerelease: false
